In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import csv
import pandas as pd
import os

In [2]:
birth_rate = []
with open('./data/birth_rate.csv', 'r') as file:
    rdr = csv.reader(file)
    for line in rdr:
        if line[2] == '합계출산율(명)': continue
        birth_rate.append(float(line[2]))
    birth_rate = np.array(birth_rate)

print(birth_rate)

[1.259 1.192 1.149 1.226 1.244 1.297 1.187 1.205 1.239 1.172 1.052 0.977
 0.918 0.837 0.808 0.778 0.72 ]


In [3]:
folder_path = './data/'

file_names = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
data_list = []

# 각 파일을 읽고 numpy.array로 변환한 후, 리스트에 저장
for file_name in file_names:
    if file_name == "birth_rate.csv": continue
    file_path = os.path.join(folder_path, file_name)
    df = pd.read_csv(file_path)  # CSV 파일 읽기
    data_array = df.values[:,1]  # pandas DataFrame을 numpy array로 변환
    data_list.append(data_array)

data_list = np.column_stack((data_list[0], data_list[1], data_list[2]))
print(data_list)

[[2.22000e+01 7.27000e+01 3.43559e+05]
 [2.33000e+01 7.94000e+01 3.27715e+05]
 [2.42000e+01 7.71000e+01 3.09759e+05]
 [2.40000e+01 7.67000e+01 3.26104e+05]
 [2.40000e+01 8.42000e+01 3.29087e+05]
 [2.36000e+01 8.34000e+01 3.27073e+05]
 [2.39000e+01 8.43000e+01 3.22807e+05]
 [2.42000e+01 8.76000e+01 3.05507e+05]
 [2.44000e+01 9.47000e+01 3.02828e+05]
 [2.56000e+01 9.66000e+01 2.81635e+05]
 [2.72000e+01 1.00100e+02 2.64455e+05]
 [2.91000e+01 9.96000e+01 2.57622e+05]
 [3.21000e+01 9.96000e+01 2.39159e+05]
 [3.02000e+01 1.10900e+02 2.13502e+05]
 [3.67000e+01 1.37300e+02 1.92507e+05]
 [4.10000e+01 1.36400e+02 1.91690e+05]
 [4.34000e+01 1.22700e+02 1.93657e+05]]


In [32]:
# 모델 구현
model2 = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(3,)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1)
])

model2.compile(optimizer='adam', loss='mean_squared_error')
model2.fit(data_list, birth_rate, epochs=300, batch_size=20)

#모델 평가
loss = model2.evaluate(data_list, birth_rate)
print(f"Model loss: {loss:.10}")

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 257029.4375
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 12252845.0000
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1189587.0000
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2312444.2500
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5585350.0000
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 3692924.7500
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 704900.5000
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 85627.6250
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1011968.8125
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1777319.6250
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1365307.2500
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 483215.1562
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3646.3760
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 280998.2812
Epoch 15/30

In [5]:
# 각 파일을 읽고 numpy.array로 변환한 후, 리스트에 저장
df = pd.read_csv('./data/educational_cost.csv')  # CSV 파일 읽기
data_array = df.values[:]  # pandas DataFrame을 numpy array로 변환
years = np.array(data_array[:,0])
Private_education  = np.array(data_array[:,1])

df = pd.read_csv('./data/house_cost.csv')  
data_array = df.values[:]  
house_cost  = np.array(data_array[:,1])

df = pd.read_csv('./data/marry_num.csv') 
data_array = df.values[:]  
marry_num  = np.array(data_array[:,1])

dataframe = pd.DataFrame({
    'Year': years,
    'education expenses': Private_education,
    'House price': house_cost,
    'Marrage Nums': marry_num
}); print(dataframe)

      Year  education expenses  House price  Marrage Nums
0   2007.0                22.2         72.7        343559
1   2008.0                23.3         79.4        327715
2   2009.0                24.2         77.1        309759
3   2010.0                24.0         76.7        326104
4   2011.0                24.0         84.2        329087
5   2012.0                23.6         83.4        327073
6   2013.0                23.9         84.3        322807
7   2014.0                24.2         87.6        305507
8   2015.0                24.4         94.7        302828
9   2016.0                25.6         96.6        281635
10  2017.0                27.2        100.1        264455
11  2018.0                29.1         99.6        257622
12  2019.0                32.1         99.6        239159
13  2020.0                30.2        110.9        213502
14  2021.0                36.7        137.3        192507
15  2022.0                41.0        136.4        191690
16  2023.0    

In [6]:
#x축, y축 설정
x = dataframe['Year'].values
y = dataframe['education expenses'].values

#y=mx+n에서 최소제곱법을 이용해 m값, n값 구하기
m1 = np.cov(x,y,ddof=1)[0,1]/np.cov(x,y,ddof=1)[0,0]
n1 = np.mean(y)-m1*np.mean(x)

print(f"Regression Equation: {m1:.5f}x{n1:.5f}")

Edu = []

m1 = float(input())
n1 = -m1 * x[-1] + y[-1]
print(f"Changed Equation: {m1:.5f}x+{n1:.5f}")
a = 2024
while a <= 2040:
    Edu.append(m1 * a + n1)
    print(f'{a}년: {(Edu[-1]):.3}만 원')
    a += 1

Regression Equation: 1.11863x-2225.85196
Changed Equation: -0.20000x+448.00000
2024년: 43.2만 원
2025년: 43.0만 원
2026년: 42.8만 원
2027년: 42.6만 원
2028년: 42.4만 원
2029년: 42.2만 원
2030년: 42.0만 원
2031년: 41.8만 원
2032년: 41.6만 원
2033년: 41.4만 원
2034년: 41.2만 원
2035년: 41.0만 원
2036년: 40.8만 원
2037년: 40.6만 원
2038년: 40.4만 원
2039년: 40.2만 원
2040년: 40.0만 원


In [34]:
#x축, y축 설정
x = dataframe['Year'].values
y = dataframe['House price'].values

#y=mx+n에서 최소제곱법을 이용해 m값, n값 구하기
m2 = np.cov(x,y,ddof=1)[0,1]/np.cov(x,y,ddof=1)[0,0]
n2 = np.mean(y)-m2*np.mean(x)

print(f"Regression Equation: {m2:.5f}x{n2:.5f}")

House = []

m2 = float(input())
n2 = -m2 * x[-1] + y[-1]
print(f"Changed Equation: {m2:.5f}x+{n2:.5f}")
a = 2024
while a <= 2040:
    House.append(m2 * a + n2)
    print(f'{a}년: {(House[-1]):.5}')
    a += 1

Regression Equation: 3.63235x-7222.52647
Changed Equation: -0.20000x+527.30000
2024년: 122.5
2025년: 122.3
2026년: 122.1
2027년: 121.9
2028년: 121.7
2029년: 121.5
2030년: 121.3
2031년: 121.1
2032년: 120.9
2033년: 120.7
2034년: 120.5
2035년: 120.3
2036년: 120.1
2037년: 119.9
2038년: 119.7
2039년: 119.5
2040년: 119.3


In [35]:
#x축, y축 설정
x = dataframe['Year'].values
y = dataframe['Marrage Nums'].values

#y=mx+n에서 최소제곱법을 이용해 m값, n값 구하기
m3 = np.cov(x,y,ddof=1)[0,1]/np.cov(x,y,ddof=1)[0,0]
n3 = np.mean(y)-m3*np.mean(x)

print(f"Regression Equation: {m3:.5f}x+{n3:.5f}")

Marrage = []

m3 = float(input())
n3 = -m3 * x[-1] + y[-1]
print(f"Changed Equation: {m3:.5f}x+{n3:.5f}")
a = 2024
while a <= 2040:
    Marrage.append(m3 * a + n3)
    print(f'{a}년: {(Marrage[-1]):.8}건')
    a += 1

Regression Equation: -10114.10294x+20658074.25000
Changed Equation: 5000.00000x+-9921343.00000
2024년: 198657.0건
2025년: 203657.0건
2026년: 208657.0건
2027년: 213657.0건
2028년: 218657.0건
2029년: 223657.0건
2030년: 228657.0건
2031년: 233657.0건
2032년: 238657.0건
2033년: 243657.0건
2034년: 248657.0건
2035년: 253657.0건
2036년: 258657.0건
2037년: 263657.0건
2038년: 268657.0건
2039년: 273657.0건
2040년: 278657.0건


In [9]:
new_data = np.column_stack((Edu, House, Marrage))
print(new_data)

[[4.32000e+01 1.22600e+02 1.98657e+05]
 [4.30000e+01 1.22500e+02 2.03657e+05]
 [4.28000e+01 1.22400e+02 2.08657e+05]
 [4.26000e+01 1.22300e+02 2.13657e+05]
 [4.24000e+01 1.22200e+02 2.18657e+05]
 [4.22000e+01 1.22100e+02 2.23657e+05]
 [4.20000e+01 1.22000e+02 2.28657e+05]
 [4.18000e+01 1.21900e+02 2.33657e+05]
 [4.16000e+01 1.21800e+02 2.38657e+05]
 [4.14000e+01 1.21700e+02 2.43657e+05]
 [4.12000e+01 1.21600e+02 2.48657e+05]
 [4.10000e+01 1.21500e+02 2.53657e+05]
 [4.08000e+01 1.21400e+02 2.58657e+05]
 [4.06000e+01 1.21300e+02 2.63657e+05]
 [4.04000e+01 1.21200e+02 2.68657e+05]
 [4.02000e+01 1.21100e+02 2.73657e+05]
 [4.00000e+01 1.21000e+02 2.78657e+05]]


In [33]:
# [사교육비(만 원), 지수(2017 = 100), 결혼(건)]
year = 2024
predictions = model2.predict(new_data)
print(predictions)
for prediction in predictions:
    print(f"{year} Predicted Birth Rate: {prediction[0]:.7}")
    year += 1

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[0.63699275]
 [0.6629937 ]
 [0.68594295]
 [0.7096246 ]
 [0.73281795]
 [0.7552789 ]
 [0.7806695 ]
 [0.8036187 ]
 [0.8254693 ]
 [0.8486627 ]
 [0.87429744]
 [0.8959039 ]
 [0.9201959 ]
 [0.9442437 ]
 [0.9674371 ]
 [0.9911187 ]
 [1.0149225 ]]
2024 Predicted Birth Rate: 0.6369928
2025 Predicted Birth Rate: 0.6629937
2026 Predicted Birth Rate: 0.6859429
2027 Predicted Birth Rate: 0.7096246
2028 Predicted Birth Rate: 0.7328179
2029 Predicted Birth Rate: 0.7552789
2030 Predicted Birth Rate: 0.7806695
2031 Predicted Birth Rate: 0.8036187
2032 Predicted Birth Rate: 0.8254693
2033 Predicted Birth Rate: 0.8486627
2034 Predicted Birth Rate: 0.8742974
2035 Predicted Birth Rate: 0.8959039
2036 Predicted Birth Rate: 0.9201959
2037 Predicted Birth Rate: 0.9442437
2038 Predicted Birth Rate: 0.9674371
2039 Predicted Birth Rate: 0.9911187
2040 Predicted Birth Rate: 1.014922
