In [4]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import csv
import pandas as pd
import os

In [27]:
birth_rate = []
with open('./data/birth_rate.csv', 'r') as file:
    rdr = csv.reader(file)
    for line in rdr:
        if line[2] == '합계출산율(명)': continue
        birth_rate.append(float(line[2]))
    birth_rate = np.array(birth_rate)

print(birth_rate)

[1.259 1.192 1.149 1.226 1.244 1.297 1.187 1.205 1.239 1.172 1.052 0.977
 0.918 0.837 0.808 0.778 0.72 ]


In [69]:
folder_path = './data/'

file_names = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
data_list = []

# 각 파일을 읽고 numpy.array로 변환한 후, 리스트에 저장
for file_name in file_names:
    if file_name == "birth_rate.csv": continue
    file_path = os.path.join(folder_path, file_name)
    df = pd.read_csv(file_path)  # CSV 파일 읽기
    data_array = df.values[:,1]  # pandas DataFrame을 numpy array로 변환
    data_list.append(data_array)

data_list = np.column_stack((data_list[0], data_list[1], data_list[2]))
print(data_list)

[[2.22000e+01 7.27000e+01 3.43559e+05]
 [2.33000e+01 7.94000e+01 3.27715e+05]
 [2.42000e+01 7.71000e+01 3.09759e+05]
 [2.40000e+01 7.67000e+01 3.26104e+05]
 [2.40000e+01 8.42000e+01 3.29087e+05]
 [2.36000e+01 8.34000e+01 3.27073e+05]
 [2.39000e+01 8.43000e+01 3.22807e+05]
 [2.42000e+01 8.76000e+01 3.05507e+05]
 [2.44000e+01 9.47000e+01 3.02828e+05]
 [2.56000e+01 9.66000e+01 2.81635e+05]
 [2.72000e+01 1.00100e+02 2.64455e+05]
 [2.91000e+01 9.96000e+01 2.57622e+05]
 [3.21000e+01 9.96000e+01 2.39159e+05]
 [3.02000e+01 1.10900e+02 2.13502e+05]
 [3.67000e+01 1.37300e+02 1.92507e+05]
 [4.10000e+01 1.36400e+02 1.91690e+05]
 [4.34000e+01 1.22700e+02 1.93657e+05]]


In [79]:
# 모델 구현
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(3,)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(data_list, birth_rate, epochs=150, batch_size=10)

#모델 평가
loss = model.evaluate(data_list, birth_rate)
print(f"Model loss: {loss:.10}")

Epoch 1/150


c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 246769200.0000  
Epoch 2/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 89791968.0000  
Epoch 3/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19978106.0000 
Epoch 4/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 751027.7500 
Epoch 5/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11340380.0000
Epoch 6/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23070742.0000 
Epoch 7/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22523018.0000 
Epoch 8/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12122400.0000 
Epoch 9/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3017258.2500 
Epoch 10/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 153162.4844
Epoch 11/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2568898.5000 
Epoch 12/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5847788.0000 
Epoch 13/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6534820.5000 
Epoch 14/150
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4188156.0000 
Epoch 1

In [80]:
new_data = np.array([[30, 120, 400000]]) # [사교육비(만 원), 지수(2017 = 100), 결혼(건)]
predictions = model.predict(new_data)
for prediction in predictions:
    print(f"Predicted Birth Rate: {prediction[0]:.2}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Predicted Birth Rate: 1.4
